/*
 * This file was generated by the mkbuiltins program.
 */

#include "shell.h"
#include "builtins.h"

int bltincmd();
int breakcmd();
int cdcmd();
int dotcmd();
int echocmd();
int evalcmd();
int execcmd();
int exitcmd();
int exportcmd();
int getoptscmd();
int hashcmd();
int jobidcmd();
int jobscmd();
int localcmd();
int pwdcmd();
int readcmd();
int returncmd();
int setcmd();
int setvarcmd();
int shiftcmd();
int trapcmd();
int truecmd();
int umaskcmd();
int unsetcmd();
int waitcmd();

int (*const builtinfunc[])() = {
	bltincmd,
	breakcmd,
	cdcmd,
	dotcmd,
	echocmd,
	evalcmd,
	execcmd,
	exitcmd,
	exportcmd,
	getoptscmd,
	hashcmd,
	jobidcmd,
	jobscmd,
	localcmd,
	pwdcmd,
	readcmd,
	returncmd,
	setcmd,
	setvarcmd,
	shiftcmd,
	trapcmd,
	truecmd,
	umaskcmd,
	unsetcmd,
	waitcmd,
};

const struct builtincmd builtincmd[] = {
	"-u", 0,
	"command", 0,
	"#", 0,
	"MUST", 0,
	"be", 0,
	"first", 0,
	"-s", 1,
	"break", 1,
	"-s", 1,
	"continue", 1,
	"-u", 2,
	"cd", 2,
	"chdir", 2,
	"-s", 3,
	".", 3,
	"-u", 4,
	"echo", 4,
	"-s", 5,
	"eval", 5,
	"-s", 6,
	"exec", 6,
	"-s", 7,
	"exit", 7,
	"-s", 8,
	"export", 8,
	"-s", 8,
	"readonly", 8,
	"-u", 9,
	"getopts", 9,
	"-u", 10,
	"hash", 10,
	"jobid", 11,
	"-u", 12,
	"jobs", 12,
	"local", 13,
	"-u", 14,
	"pwd", 14,
	"-u", 15,
	"read", 15,
	"-s", 16,
	"return", 16,
	"-s", 17,
	"set", 17,
	"setvar", 18,
	"-s", 19,
	"shift", 19,
	"-s", 20,
	"trap", 20,
	"-s", 21,
	":", 21,
	"-u", 21,
	"true", 21,
	"-u", 22,
	"umask", 22,
	"-s", 23,
	"unset", 23,
	"-u", 24,
	"wait", 24,
	NULL, 0
};
