/*
 * This file was generated by the mkbuiltins program.
 */

#define BLTINCMD 0
#define BREAKCMD 1
#define CDCMD 2
#define DOTCMD 3
#define ECHOCMD 4
#define EVALCMD 5
#define EXECCMD 6
#define EXITCMD 7
#define EXPORTCMD 8
#define GETOPTSCMD 9
#define HASHCMD 10
#define JOBIDCMD 11
#define JOBSCMD 12
#define LOCALCMD 13
#define PWDCMD 14
#define READCMD 15
#define RETURNCMD 16
#define SETCMD 17
#define SETVARCMD 18
#define SHIFTCMD 19
#define TRAPCMD 20
#define TRUECMD 21
#define UMASKCMD 22
#define UNSETCMD 23
#define WAITCMD 24

struct builtincmd {
      char *name;
      int code;
};

extern int (*const builtinfunc[])();
extern const struct builtincmd builtincmd[];
