/*
 * This file was generated by the mkbuiltins program.
 */

#define BLTINCMD 0
#define ALIASCMD 1
#define BREAKCMD 2
#define CDCMD 3
#define DOTCMD 4
#define ECHOCMD 5
#define EVALCMD 6
#define EXECCMD 7
#define EXITCMD 8
#define EXPCMD 9
#define EXPORTCMD 10
#define FALSECMD 11
#define FDFLAGSCMD 12
#define GETOPTSCMD 13
#define HASHCMD 14
#define HISTCMD 15
#define INPUTRC 16
#define JOBIDCMD 17
#define JOBSCMD 18
#define KILLCMD 19
#define LOCALCMD 20
#define PRINTFCMD 21
#define PWDCMD 22
#define READCMD 23
#define RETURNCMD 24
#define SETCMD 25
#define SETVARCMD 26
#define SHIFTCMD 27
#define SPECIALVARCMD 28
#define TESTCMD 29
#define TIMESCMD 30
#define TRAPCMD 31
#define TRUECMD 32
#define TYPECMD 33
#define ULIMITCMD 34
#define UMASKCMD 35
#define UNALIASCMD 36
#define UNSETCMD 37
#define WAITCMD 38
#define WORDEXPCMD 39
#define DEBUGCMD 40

struct builtincmd {
      char *name;
      int code;
};

extern int (*const builtinfunc[])();
extern const struct builtincmd builtincmd[];
