/*
 * This file was generated by the mkbuiltins program.
 */


struct builtincmd {
      char *name;
      int code;
};

extern int (*const builtinfunc[])();
extern const struct builtincmd builtincmd[];
